namespace RogueLibsCore
{
	public static class VanillaEffects
	{
		public const string
			AbovetheLaw = "AboveTheLaw",
			AccuracyBoosted = "Accurate",
			Acid = "Acid",
			AllStatsDecreased = "DecreaseAllStats",
			AlwaysCrit = "AlwaysCrit",
			BadVision = "BadVision",
			ChargeLevel1 = "ChargeLevel1",
			ChargeLevel2 = "ChargeLevel2",
			ChargeLevel3 = "ChargeLevel3",
			ChargeLevel4 = "ChargeLevel4",
			Confused = "Confused",
			CopDebt1 = "OweCops1",
			CopDebt2 = "OweCops2",
			Cyanide = "Cyanide",
			DeliveringPackage = "DeliverPackage",
			Dizzy = "Dizzy",
			DNAConnection = "ZombieSpirit",
			Drunk = "Drunk",
			Electrocuted = "Electrocuted",
			ElectroTouch = "ElectroTouch",
			Fast = "Fast",
			FeelingGood = "FeelingGood",
			FeelingLucky = "FeelingLucky",
			FeelingUnlucky = "FeelingUnlucky",
			Frozen = "Frozen",
			Giant = "Giant",
			HearingBlocked = "HearingBlocked",
			IgnoreLasers = "IgnoreLasers",
			IncreaseAllStats = "IncreaseAllStats",
			InDebt1 = "InDebt",
			InDebt2 = "InDebt2",
			InDebt3 = "InDebt3",
			Invincible = "Invincible",
			Invisible = "Invisible",
			InvisiblePermanent = "InvisiblePermanent",
			InvisibleTemporary = "InvisibleLimited",
			KillerThrower = "KillerThrower",
			Loud = "Loud",
			MindControlling = "MindControlling",
			NiceSmelling = "NiceSmelling",
			Nicotine = "Nicotine",
			NumbtoPain = "NumbToPain",
			OnFire = "OnFire",
			Paralyzed = "Paralyzed",
			Poisoned = "Poisoned",
			Rage = "Enraged",
			RegenerateHealth = "RegenerateHealth",
			RegenerateHealthFaster = "RegenerateHealthFaster",
			ResistBulletsSmall = "ResistBulletsSmall",
			ResistDamageLarge = "ResistDamageLarge",
			ResistDamageMedium = "ResistDamageMed",
			ResistDamageSmall = "ResistDamageSmall",
			ResistFire = "ResistFire",
			Resurrection = "Resurrection",
			RevenueExtortion = "Revenue",
			Shrunk = "Shrunk",
			Slow = "Slow",
			StableSystem = "BlockDebuffs",
			Strength = "Strength",
			SuperDizzy = "DizzyB",
			Tranquilized = "Tranquilized",
			Weak = "Weak",
			Werewolf = "WerewolfEffect",
			Withdrawal = "Withdrawal";
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}