namespace RogueLibsCore
{
	public static class VanillaObjects
	{
		public const string
			AirConditioner = "AirConditioner",
			AlarmButton = "AlarmButton",
			Altar = "Altar",
			AmmoDispenser = "AmmoDispenser",
			ArcadeGame = "ArcadeGame",
			ATMMachine = "ATMMachine",
			AugmentationBooth = "AugmentationBooth",
			Barbecue = "Barbecue",
			BarStool = "BarStool",
			Bathtub = "Bathtub",
			Bed = "Bed",
			Boulder = "Boulder",
			BoulderSmall = "BoulderSmall",
			Bush = "Bush",
			CapsuleMachine = "CapsuleMachine",
			Chair = "Chair",
			Chair2 = "Chair2",
			Chest = "ChestBasic",
			CloneMachine = "CloneMachine",
			Computer = "Computer",
			Counter = "Counter",
			Crate = "Crate",
			Desk = "Desk",
			Door = "Door",
			Elevator = "Elevator",
			EventTriggerFloor = "EventTriggerFloor",
			ExplodingBarrel = "ExplodingBarrel",
			FireHydrant = "FireHydrant",
			Fireplace = "Fireplace",
			FireSpewer = "FireSpewer",
			FlameGrate = "FlameGrate",
			FlamingBarrel = "FlamingBarrel",
			GasVent = "GasVent",
			Generator = "Generator",
			GeneratorOverclocked = "Generator2",
			Gravestone = "Gravestone",
			Jukebox = "Jukebox",
			KillerPlant = "KillerPlant",
			Lamp = "Lamp",
			LaserEmitter = "LaserEmitter",
			LoadoutMachine = "LoadoutMachine",
			Manhole = "Manhole",
			Mine = "Mine",
			MovieScreen = "MovieScreen",
			PawnShopMachine = "PawnShopMachine",
			Plant = "Plant",
			Podium = "Podium",
			PoliceBox = "PoliceBox",
			PoolTable = "PoolTable",
			PowerBox = "PowerBox";
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}