// ReSharper disable IdentifierTypo InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedType.Global
namespace RogueLibsCore
{
#pragma warning disable IDE0079 // Remove unnecessary suppression
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public static class VanillaObjects
    {
        public const string
            AirConditioner = "AirConditioner",
            AlarmButton = "AlarmButton",
            Altar = "Altar",
            AmmoDispenser = "AmmoDispenser",
            ArcadeGame = "ArcadeGame",
            ATMMachine = "ATMMachine",
            AugmentationBooth = "AugmentationBooth",
            Barbecue = "Barbecue",
            BarStool = "BarStool",
            Bathtub = "Bathtub",
            Bed = "Bed",
            Boulder = "Boulder",
            BoulderSmall = "BoulderSmall",
            Bush = "Bush",
            CapsuleMachine = "CapsuleMachine",
            Chair = "Chair",
            Chair2 = "Chair2",
            Chest = "ChestBasic",
            CloneMachine = "CloneMachine",
            Computer = "Computer",
            Counter = "Counter",
            Crate = "Crate",
            Desk = "Desk",
            Door = "Door",
            Elevator = "Elevator",
            EventTriggerFloor = "EventTriggerFloor",
            ExplodingBarrel = "ExplodingBarrel",
            FireHydrant = "FireHydrant",
            Fireplace = "Fireplace",
            FireSpewer = "FireSpewer",
            FlameGrate = "FlameGrate",
            FlamingBarrel = "FlamingBarrel",
            GasVent = "GasVent",
            Generator = "Generator",
            GeneratorOverclocked = "Generator2",
            Gravestone = "Gravestone",
            Jukebox = "Jukebox",
            KillerPlant = "KillerPlant",
            Lamp = "Lamp",
            LaserEmitter = "LaserEmitter",
            LoadoutMachine = "LoadoutMachine",
            Manhole = "Manhole",
            Mine = "Mine",
            MovieScreen = "MovieScreen",
            PawnShopMachine = "PawnShopMachine",
            Plant = "Plant",
            Podium = "Podium",
            PoliceBox = "PoliceBox",
            PoolTable = "PoolTable",
            PowerBox = "PowerBox",
            Refrigerator = "Refrigerator",
            Safe = "Safe",
            SatelliteDish = "SatelliteDish",
            SecurityCam = "SecurityCam",
            Shelf = "Shelf",
            Sign = "Sign",
            SlimeBarrel = "SlimeBarrel",
            SlimePuddle = "SlimePuddle",
            SlotMachine = "SlotMachine",
            Speaker = "Speaker",
            Stove = "Stove",
            SwitchBasic = "SwitchBasic",
            SwitchFloor = "SwitchFloor",
            Table = "Table",
            TableBig = "TableBig",
            Television = "Television",
            Toilet = "Toilet",
            TrashCan = "TrashCan",
            Tree = "Tree",
            Tube = "Tube",
            Turntables = "Turntables",
            Turret = "Turret",
            VendorCart = "VendorCart",
            WaterPump = "WaterPump",
            Well = "Well",
            Window = "Window";
    }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
#pragma warning restore IDE0079 // Remove unnecessary suppression
}
