name: Bug Report
description: File a bug report
title: "[Bug] "
labels: [bug]
assignees:
  - SugarBarrel
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Ex. When you [...] and then [...], [...] happens.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Ex. When you [...] and then [...], [...] doesn't happen.
    validations:
      required: true
  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots and logs
      description: Attach any relevant screenshots or output logs here.
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you on?
      options:
        - Windows 64-bit
        - Windows 32-bit
        - Linux
        - macOS
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: What version of the game are you running?
      options:
        - v98
        - v97
        - v96
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of RogueLibs are you running?
      placeholder: Ex. v3.5.0-rc.4
    validations:
      required: true
  - type: input
    id: installed-mods
    attributes:
      label: Installed mods
      description: A list of your installed mods.
      placeholder: Ex. ECTD, SpritePackLoader...
