blank_issues_enabled: false
contact_links:
  - name: Streets of Rogue Discord
    url: https://discord.gg/m3zuHSwQw2
    about: "Talk about mod development and report smaller issues here. You'll most likely get faster support on Discord."
  - name: RogueLibs Discussions
    url: https://github.com/Abbysssal/RogueLibs/discussions/new?category=q-a
    about: "Not sure how to make something work? Start a discussion here."
