name: Documentation Issue
description: Anything related to documentation.
title: "[Documentation]: "
labels: [documentation]
assignees:
  - Abbysssal
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: page
    attributes:
      label: Is the issue related to an existing page?
      description: If so, provide a link to that page
      placeholder: Ex. https://abbysssal.github.io/RogueLibs/docs/intro
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: A clear and concise description of why you want to do the proposed change.
      placeholder: |
        Ex. I don't like [...] in [...]; it looks [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: |
        Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        Ex. I want [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions you've considered.
      placeholder: |
        Ex. As an alternative, you could [...]; or even [...]
